CREATE TABLE Portfolio
(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	PortfolioName TEXT NOT NULL
);

CREATE TABLE PortfolioValuation
(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	PortfolioId INTEGER NOT NULL,
	ValuationDate DATETIME NOT NULL,
	Value REAL NOT NULL,
	FOREIGN KEY(PortfolioId) REFERENCES Portfolio(Id)
);

CREATE TABLE HoldingValuation
(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	PortfolioId INTEGER NOT NULL,
	ValuationDate DATETIME NOT NULL,
	Symbol TEXT NOT NULL,
	Value REAL NOT NULL,
	FOREIGN KEY(PortfolioId) REFERENCES Portfolio(Id)
);